In [68]:
import pandas as pd
import numpy as np
from datetime import datetime as dt

In [69]:
file_to_load = "shark_attacks.csv"
df = pd.read_csv(file_to_load)
df.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-18,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,9-Jun-18,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,8-Jun-18,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,4-Jun-18,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [70]:
#Drop data before 1975
df_1975 = df[df["Year"]>=1975]
df_1975.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-18,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,9-Jun-18,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,8-Jun-18,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,4-Jun-18,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

In [71]:
#Case Number is a better date indicator than other date column, the following code is meant to take the Case Number
# create a new column out of it and convert it to a date format
# first bit of code is to remove dates that have no month/day, just year
df_1975['Attack Date'] = df_1975["Case Number"].str.contains("00.00")==False
df_1975_clean = df_1975[df_1975['Attack Date']==True]

#this removes the extra digits on the case number, i.e. if multiple happened one day they are appended with a suffix of a,b,c
df_1975_clean['Attack Date'] = df_1975_clean['Case Number'].str[:10]
df_1975_clean

<ipython-input-71-61b7f443faa1>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1975['Attack Date'] = df_1975["Case Number"].str.contains("00.00")==False
<ipython-input-71-61b7f443faa1>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1975_clean['Attack Date'] = df_1975_clean['Case Number'].str[:10]

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Attack Date
0,2018.06.25,25-Jun-18,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,2018.06.25
1,2018.06.18,18-Jun-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,2018.06.18
2,2018.06.09,9-Jun-18,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,2018.06.09
3,2018.06.08,8-Jun-18,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,2018.06.08
4,2018.06.04,4-Jun-18,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,2018.06.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3240,1975.02.10,10-Feb-75,1975.0,Unprovoked,AUSTRALIA,South Australia,(Point Sinclair) Penong,Swimming underwater from crayfish cage to a fi...,Wade Shipard,M,...,"A. Sharpe, pp.124-125; Sydney Morning Herald,...",1975.02.10-Shipard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.10,1975.02.10,3063.0,NaN,NaN,1975.02.10
3241,1975.02.09,9-Feb-75,1975.0,Unprovoked,AUSTRALIA,Victoria,Anglesea,Crayfishing,John Lear,M,...,"The Age, 2/11/1975",1975.02.09-Lear.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.09,1975.02.09,3062.0,NaN,NaN,1975.02.09
3242,1975.02.07,7-Feb-75,1975.0,Unprovoked,AUSTRALIA,Queensland,Currumbin Rock,NaN,M. Worman,M,...,"J. Green, p. 36",1975.02.07-Worman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.07,1975.02.07,3061.0,NaN,NaN,1975.02.07
3243,1975.02.01,1-Feb-75,1975.0,Provoked,SOUTH AFRICA,Western Cape Province,"Beespens, False Bay",Fishing,Gerhard Visser,M,...,"The Argus, 2/3/1975",1975.02.01-Visser.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.01,1975.02.01,3060.0,NaN,NaN,1975.02.01
3244,1975.01.19,19-Jan-75,1975.0,Unprovoked,AUSTRALIA,South Australia,Coffin Bay,Surfing,David Barrowman,M,...,"J. West; Adelaide Advertiser, 1/20/1975; P. Ke...",1975.01.19-Barrowman.pdf,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.01.19,1975.01.19,3059.0,NaN,NaN,1975.01.19

In [72]:
#replacing the periods with hyphens, hoping this can be used to create a date format later
df_1975_clean['Attack Date'] = df_1975_clean['Attack Date'].str.replace('.','-')
df_1975_clean

<ipython-input-72-5c6c0ced3f84>:2: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will*not* be treated as literal strings when regex=True.
  df_1975_clean['Attack Date'] = df_1975_clean['Attack Date'].str.replace('.','-')
<ipython-input-72-5c6c0ced3f84>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1975_clean['Attack Date'] = df_1975_clean['Attack Date'].str.replace('.','-')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Attack Date
0,2018.06.25,25-Jun-18,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,2018-06-25
1,2018.06.18,18-Jun-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson�McNeely,F,...,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,2018-06-18
2,2018.06.09,9-Jun-18,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,2018-06-09
3,2018.06.08,8-Jun-18,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,2018-06-08
4,2018.06.04,4-Jun-18,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,2018-06-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3240,1975.02.10,10-Feb-75,1975.0,Unprovoked,AUSTRALIA,South Australia,(Point Sinclair) Penong,Swimming underwater from crayfish cage to a fi...,Wade Shipard,M,...,"A. Sharpe, pp.124-125; Sydney Morning Herald,...",1975.02.10-Shipard.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.10,1975.02.10,3063.0,NaN,NaN,1975-02-10
3241,1975.02.09,9-Feb-75,1975.0,Unprovoked,AUSTRALIA,Victoria,Anglesea,Crayfishing,John Lear,M,...,"The Age, 2/11/1975",1975.02.09-Lear.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.09,1975.02.09,3062.0,NaN,NaN,1975-02-09
3242,1975.02.07,7-Feb-75,1975.0,Unprovoked,AUSTRALIA,Queensland,Currumbin Rock,NaN,M. Worman,M,...,"J. Green, p. 36",1975.02.07-Worman.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.07,1975.02.07,3061.0,NaN,NaN,1975-02-07
3243,1975.02.01,1-Feb-75,1975.0,Provoked,SOUTH AFRICA,Western Cape Province,"Beespens, False Bay",Fishing,Gerhard Visser,M,...,"The Argus, 2/3/1975",1975.02.01-Visser.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.02.01,1975.02.01,3060.0,NaN,NaN,1975-02-01
3244,1975.01.19,19-Jan-75,1975.0,Unprovoked,AUSTRALIA,South Australia,Coffin Bay,Surfing,David Barrowman,M,...,"J. West; Adelaide Advertiser, 1/20/1975; P. Ke...",1975.01.19-Barrowman.pdf,NaN,http://sharkattackfile.net/spreadsheets/pdf_di...,1975.01.19,1975.01.19,3059.0,NaN,NaN,1975-01-19

In [105]:
#create a new dataframe with only the important columns ##NOTE. this could probably be done earlier.
shark_trim = df_1975_clean[["Attack Date","Year","Type","Country","Area","Location","Activity","Sex ","Age","Injury","Fatal (Y/N)","Species "]]
shark_trim

,Attack Date,Year,Type,Country,Area,Location,Activity,Sex,Age,Injury,Fatal (Y/N),Species
0,2018-06-25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,F,57,"No injury to occupant, outrigger canoe and pad...",N,White shark
1,2018-06-18,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,F,11,Minor injury to left thigh,N,NaN
2,2018-06-09,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,M,48,Injury to left lower leg from surfboard skeg,N,NaN
3,2018-06-08,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,M,NaN,Minor injury to lower leg,N,2 m shark
4,2018-06-04,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,M,NaN,Lacerations to leg & hand shark PROVOKED INCIDENT,N,"Tiger shark, 3m"
...,...,...,...,...,...,...,...,...,...,...,...,...
3240,1975-02-10,1975.0,Unprovoked,AUSTRALIA,South Australia,(Point Sinclair) Penong,Swimming underwater from crayfish cage to a fi...,M,12,Right leg severed FATAL,Y,"White shark, 3 m [10']"
3241,1975-02-09,1975.0,Unprovoked,AUSTRALIA,Victoria,Anglesea,Crayfishing,M,45,Puncture wounds to right shoulder,N,"Carpet shark, 10'"
3242,1975-02-07,1975.0,Unprovoked,AUSTRALIA,Queensland,Currumbin Rock,NaN,M,NaN,Survived,N,NaN
3243,1975-02-01,1975.0,Provoked,SOUTH AFRICA,Western Cape Province,"Beespens, False Bay",Fishing,M,12,Foot bitten by shark he was gaffing PROVOKED ...,N,"Copper shark, 50-kg [110-b]"
3244,1975-01-19,1975.0,Unprovoked,AUSTRALIA,South Australia,Coffin Bay,Surfing,M,17,"FATAL, body not recovered",Y,NaN

In [106]:
shark_trim["Type"].value_counts()
#need to harmonize the Boating, Boat, Boatomg into Boating // maybe make "Invalid" and "Questionable" to "Unknown Activity"

Unprovoked      2499
Invalid          260
Provoked         232
Boating           91
Boat              61
Sea Disaster      44
Questionable       2
Boatomg            1
Name: Type, dtype: int64

In [107]:
shark_trim["Country"].unique()
#This looks OK, probably a few to clean up like "South China Sea", maybe we can compare to a countries of the world?

array(['USA', 'AUSTRALIA', 'MEXICO', 'BRAZIL', 'ENGLAND', 'SOUTH AFRICA',
       'THAILAND', 'COSTA RICA', 'MALDIVES', 'BAHAMAS', 'NEW CALEDONIA',
       'ECUADOR', 'MALAYSIA', 'LIBYA', nan, 'CUBA', 'MAURITIUS',
       'NEW ZEALAND', 'SPAIN', 'SAMOA', 'SOLOMON ISLANDS', 'JAPAN',
       'EGYPT', 'ST HELENA, British overseas territory', 'COMOROS',
       'REUNION', 'FRENCH POLYNESIA', 'UNITED KINGDOM',
       'UNITED ARAB EMIRATES', 'PHILIPPINES', 'INDONESIA', 'CHINA',
       'COLUMBIA', 'CAPE VERDE', 'Fiji', 'DOMINICAN REPUBLIC',
       'CAYMAN ISLANDS', 'ARUBA', 'MOZAMBIQUE', 'FIJI', 'PUERTO RICO',
       'ITALY', 'ATLANTIC OCEAN', 'GREECE', 'ST. MARTIN', 'FRANCE',
       'PAPUA NEW GUINEA', 'TRINIDAD & TOBAGO', 'KIRIBATI', 'ISRAEL',
       'DIEGO GARCIA', 'TAIWAN', 'JAMAICA', 'PALESTINIAN TERRITORIES',
       'GUAM', 'SEYCHELLES', 'BELIZE', 'NIGERIA', 'TONGA', 'SCOTLAND',
       'CANADA', 'CROATIA', 'SAUDI ARABIA', 'CHILE', 'ANTIGUA', 'KENYA',
       'RUSSIA', 'TURKS & CAICOS', 'UNITED ARAB EMIRATES (UAE)', 'AZORES',
       'SOUTH KOREA', 'MALTA', 'VIETNAM', 'MADAGASCAR', 'PANAMA',
       'SOMALIA', 'NEVIS', 'BRITISH VIRGIN ISLANDS', 'NORWAY', 'SENEGAL',
       'YEMEN', 'GULF OF ADEN', 'Sierra Leone', 'ST. MAARTIN',
       'GRAND CAYMAN', 'Seychelles', 'LIBERIA', 'VANUATU', 'MEXICO ',
       'HONDURAS', 'VENEZUELA', 'SRI LANKA', ' TONGA', 'URUGUAY', 'INDIA',
       'MICRONESIA', 'CARIBBEAN SEA', 'OKINAWA', 'TANZANIA',
       'MARSHALL ISLANDS', 'EGYPT / ISRAEL', 'NORTHERN ARABIAN SEA',
       'HONG KONG', 'EL SALVADOR', 'TUNISIA', 'NAMIBIA', 'BERMUDA',
       'PORTUGAL', 'SOUTH CHINA SEA', 'BANGLADESH'], dtype=object)

In [108]:
#definite opportunity to clean this up
shark_trim["Activity"].value_counts()

Surfing                                  906
Swimming                                 398
Spearfishing                             197
Fishing                                  160
Wading                                   104
                                        ...
Surfing, but lying prone on his board      1
Kitesurfing                                1
Fishing for squid                          1
Watching seals                             1
Fishing for blue sharks                    1
Name: Activity, Length: 545, dtype: int64

In [109]:
#species may need an extra bit of work to be done, we may need to create a generic shark based on "most likely in area" or by "Size"
shark_trim["Species "].value_counts()

White shark                                           110
Shark involvement not confirmed                        67
Shark involvement prior to death was not confirmed     54
Tiger shark                                            46
Invalid                                                41
                                                     ...
4 to 5m white shark                                     1
Tiger sharks in area                                    1
170-kg, 2.8 m shark                                     1
White shark, 5 m to 6 m [16.5' to 20']                  1
Tiger shark, 6'                                         1
Name: Species , Length: 1003, dtype: int64

In [110]:
shark_trim["Fatal (Y/N)"].value_counts()
# need to just move all the randos into unknown or make a call to make them "N" if they are unknown?

N          2595
Y           329
UNKNOWN      20
2017          1
M             1
Name: Fatal (Y/N), dtype: int64

In [111]:
#is there a way to use this DF to do the replace based on the string? like change all these to Surfing?
surfs_up = shark_trim[shark_trim['Activity'].str.contains('Surf', na=False)]
surfs_up['Activity'].value_counts()

Surfing                                                906
Surf-skiing                                             10
Surf fishing                                             7
Surf skiing                                              7
Surfing (sitting on his board)                           7
Kite Surfing                                             6
Surf skiing                                              6
Surfing                                                  4
Surfing, paddling seawards                               3
Surfing (lying prone on his board)                       2
Standing / Surfing                                       2
Surfing, collided with shark                             2
Surfing, fell off surfboard & stepped on the shark.      1
Surfing with dolphins                                    1
Boogie boarding or Surfing                               1
Surfing / treading water                                 1
Surfing, lying on surfboard                              1
Wading / Surfing                                         1
Surfing, paddling shorewards                             1
Surfng                                                   1
Surfing (or sailboarding)                                1
Surfing, but standing in water alongside board           1
Surfing, but lying prone on his board                    1
Fishing from Surfboard                                   1
Treading water/ Surfing                                  1
Surf fishing / wading                                    1
Surfing, fell off surfboard                              1
Surfing & filming dolphins                               1
Surfing & dangling foot in water amid baitfish           1
Surf paddling                                            1
Swimming / Body Surfing                                  1
Surfing (or body boarding)                               1
Surfing / Wading                                         1
Surfing, sitting on board                                1
Surfing or body surfing                                  1
Night Surfing                                            1
Surfing amid a shoal of sharks                           1
Surfing / Swimming                                       1
Name: Activity, dtype: int64

In [112]:
#is there a way to use this DF to do the replace based on the string? like change all these to Swimming?
swim = shark_trim[shark_trim['Activity'].str.contains('Swim', na=False)]
swim['Activity'].value_counts()

Swimming                                                                 398
Swimming                                                                  14
Swimming or surfing                                                        2
Swimming / Wading                                                          2
Swimming / snorkeling                                                      2
Swimming from the New Venture                                              2
Swimming alongside NOAA research vessel Discoverer                         2
Swimming, towing a kayak                                                   1
Swimming from makeshift raft  to life vest after fishing boat sank         1
Swimming to shore from boat or kayak                                       1
Swimming or paddle boarding                                                1
Swimming in canal                                                          1
Swimming, poaching abalone                                                 1
Swimming behind sailboat                                                   1
Swimming /  boogie boarding                                                1
Swimming near his boat                                                     1
Swimming & snorkeling                                                      1
Swimming breast stoke                                                      1
Swimming with dolphins                                                     1
Swimming with pod of dolphins                                              1
Swimming after falling overboard                                           1
Swimming, after falling off towed kneeboard                                1
Swimming / treading water                                                  1
Swimming with mask & snorkel                                               1
Swimming in strong current with 3 others when he disappeared               1
Swimming / surfing                                                         1
Swimming / shipwreck                                                       1
Swimming to shore with floatioon devices after boat engine conked out      1
Swimming with boogie board                                                 1
Swimming, attempting to rescue a girl  believed to be drowning             1
Swimming, towing surfboard                                                 1
Swimming, after single-engine aircraft went down in the sea                1
Swimming to shore from capsized kayak                                      1
Swimming / Body surfing                                                    1
Swimming back from anchored sailboat                                       1
Swimming after boat became disabled                                        1
Swimming underwater from crayfish cage to a fishing bait                   1
Swimming from shore to anchored sailboat                                   1
Swimming or snorkeling                                                     1
Swimming or boogie boarding                                                1
Swimming, wearing black wetsuit & swim fins                                1
Swimming (using a float)                                                   1
Swimming /  Whale Watching                                                 1
Swimming near pod of whales                                                1
Swimming / Body Surfing                                                    1
Swimming out to porpoises                                                  1
Swimming or Snorkeling                                                     1
Surfing / Swimming                                                         1
Swimming after being swept into sea by a large wave                        1
Swimming / jumping off a jetty                                             1
Swimming, poaching perlemoen                                               1
Swimming in fish tank                                                      1
Name: Activity, dtype: int64

In [113]:
#can we loop through this somehow and pull for like Tiger, White, Bull, etc?
shark_types = shark_trim[shark_trim['Species '].str.contains('White', na=False)]
shark_types['Species '].value_counts()

White shark                              110
White shark, 3.5 m                         6
White shark, 4 m [13']                     4
White shark, 5 m [16.5']                   4
White shark, 8' to 10'                     4
                                        ...
White shark x 2                            1
White shark, 5' to 6' juvenile             1
White shark or oceanic whitetip shark      1
White shark, 4.5 m [14'9"]                 1
White shark, >6'                           1
Name: Species , Length: 112, dtype: int64

In [114]:
#Simple replace for the Type
shark_trim["Type"] = shark_trim.loc[:,"Type"].replace(
    {"Boat": "Boating",
     "Boatomg": "Boating",
     "Questionable":"Unknown",
     "Invalid":"Unknown"})
shark_trim["Type"].value_counts()

<ipython-input-114-1e3c587dd055>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shark_trim["Type"] = shark_trim.loc[:,"Type"].replace(

Unprovoked      2499
Unknown          262
Provoked         232
Boating          153
Sea Disaster      44
Name: Type, dtype: int64

In [128]:
#Trying to figure out how to do the update by string characteristics as opposed ot just writing out each item like the Type
shark_trim.loc[shark_trim['Activity'].str.contains('surf', na =False,case=False), 'Activity'] = 'Surfing'
shark_trim["Activity"].value_counts()

Surfing                                                           1104
Swimming                                                           398
Spearfishing                                                       197
Fishing                                                            160
Wading                                                             104
                                                                  ...
Scuba diving                                                         1
Spearfishing (Free diving)                                           1
Sailboarding, fell into water 100 yards outside the breakwater       1
Snorkeling, possibly holding a fish                                  1
Standing                                                             1
Name: Activity, Length: 453, dtype: int64

In [129]:
#Trying to figure out how to do the update by string characteristics as opposed ot just writing out each item like the Type
shark_trim.loc[shark_trim['Activity'].str.contains('swim', na =False,case=False), 'Activity'] = 'Swimming'
shark_trim["Activity"].value_counts()

Surfing                                                           1104
Swimming                                                           466
Spearfishing                                                       197
Fishing                                                            160
Wading                                                             104
                                                                  ...
Sailboarding, fell into water 100 yards outside the breakwater       1
Snorkeling, possibly holding a fish                                  1
Abalone diving using Hookah (near calving whales)                    1
On a float                                                           1
Standing                                                             1
Name: Activity, Length: 403, dtype: int64

In [130]:
#Trying to figure out how to do the update by string characteristics as opposed ot just writing out each item like the Type
shark_trim.loc[shark_trim['Activity'].str.contains('fish', na =False,case=False), 'Activity'] = 'Fishing'
shark_trim["Activity"].value_counts()

Surfing                                                  1104
Fishing                                                   517
Swimming                                                  466
Wading                                                    104
Snorkeling                                                 83
                                                         ...
Conducting research                                         1
Onboard 21' powerboat that capsized in rough seas           1
Explosion destroyed 28' boat, survivors in the water        1
Diving / Kissing the shark                                  1
Standing                                                    1
Name: Activity, Length: 296, dtype: int64

In [131]:
#Trying to figure out how to do the update by string characteristics as opposed ot just writing out each item like the Type
shark_trim.loc[shark_trim['Activity'].str.contains('scuba', na =False,case=False), 'Activity'] = 'Scuba Diving'
shark_trim["Activity"].value_counts()

Surfing                                              1104
Fishing                                               517
Swimming                                              466
Wading                                                104
Scuba Diving                                           87
                                                     ...
Touching sharks                                         1
Floating on an inflatable raft                          1
Conducting research                                     1
Onboard 21' powerboat that capsized in rough seas       1
Standing                                                1
Name: Activity, Length: 283, dtype: int64